export const TOKEN_TYPES = {
    DOCTYPE: "DOCTYPE",
    KEYWORD: "KEYWORD",
    STRING: "STRING",
    TEXT: "TEXT",
    FUNCTIONCALL: "FUNCTIONCALL",
    ESCAPE: "ESCAPE",
    LPARENT: "LPARENT",
    RPARENT: "RPARENT",
    LCBRACE: "LCBRACE",
    RCBRACE: "RCBRACE",
    OPENINGTAG: "OPENINGTAG",
    CLOSINGTAG: "CLOSINGTAG",
    SELFCLOSINGTAG: "SELFCLOSINGTAG",
    PARAMETEREXPRESSION: "PARAMETEREXPRESSION",
    LESSTHAN: "LESSTHAN",
    CONDITION: "CONDITION",
    CODEBLOCK: "CODEBLOCK",
    EACHEXPRESSION: "EACHEXPRESSION"
};

export type TokenType = typeof TOKEN_TYPES[keyof typeof TOKEN_TYPES];