export default [
    { fnName: "PI", fnParams: [], fnBody: `return Math.PI` },
    { fnName: "E", fnParams: [], fnBody: `return Math.E` },
    { fnName: "SQRT2", fnParams: [], fnBody: `return Math.SQRT2` },
    { fnName: "SQRT12", fnParams: [], fnBody: `return Math.SQRT1_2` },
    { fnName: "LN2", fnParams: [], fnBody: `return Math.LN2` },
    { fnName: "LN10", fnParams: [], fnBody: `return Math.LN10` },
    { fnName: "LOG2E", fnParams: [], fnBody: `return Math.LOG2E` },
    { fnName: "LOG10E", fnParams: [], fnBody: `return Math.LOG10E` },
    { fnName: "round", fnParams: ['num'], fnBody: `return Math.round(Number(num))` },
    { fnName: "ceil", fnParams: ['num'], fnBody: `return Math.ceil(Number(num))` },
    { fnName: "floor", fnParams: ['num'], fnBody: `return Math.floor(Number(num))` },
    { fnName: "trunc", fnParams: ['num'], fnBody: `return Math.trunc(Number(num))` },
    { fnName: "sign", fnParams: ['num'], fnBody: `return Math.sign(Number(num))` },
    { fnName: "pow", fnParams: ['num1', 'num2'], fnBody: `return Math.pow(Number(num1), Number(num2))` },
    { fnName: "sqrt", fnParams: ['num'], fnBody: `return Math.sqrt(Number(num))` },
    { fnName: "abs", fnParams: ['num'], fnBody: `return Math.abs(Number(num))` },
    { fnName: "sin", fnParams: ['num'], fnBody: `return Math.sin(Number(num))` },
    { fnName: "cos", fnParams: ['num'], fnBody: `return Math.cos(Number(num))` },
    { fnName: "tan", fnParams: ['num'], fnBody: `return Math.tan(Number(num))` },
    { fnName: "random", fnParams: [], fnBody: `return Math.random()` },
    { fnName: "log", fnParams: ['num'], fnBody: `return Math.log(Number(num))` },
    { fnName: "log2", fnParams: ['num'], fnBody: `return Math.log2(Number(num))` },
    { fnName: "log10", fnParams: ['num'], fnBody: `return Math.log10(Number(num))` },

]